name: Container on Kubernetes

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string

jobs:

  build:
    name: BUILD
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 oi ${{ inputs.username }}"
      - run: printenv | sort
      
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - run: ls
      - run: ls .github || true
      - run: ls .github/workflows  || true
      - run: ls .github/actions  || true
      
      - uses: actions/checkout@v3
        with:
         repository: defaultbr/cicd-base
         token: ${{ secrets.GITHUB_TOKEN }}
         ref: main    
       
      
      - run: ls
      - run: ls .github || true
      - run: ls .github/workflows  || true
      - run: ls .github/actions  || true
            
      
      - id: foo
        uses: ./.github/actions/build-container
        with:
          environment: test
          secret_qualquer: secret_qualquer
          tag: tag:abc1
          
          

#       - run: echo random-number ${{ steps.foo.outputs.random-number }}
#         shell: bash
        
#   TEST:
#     name: TEST
#     runs-on: ubuntu-latest
#     needs:
#       - BUILD
#     steps:
#       - run: echo "🎉 oi ${{ inputs.username }}"
#       - run: printenv | sort      
      
#   CD:
#     name: CD
#     needs:
#       - TEST
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - run: echo "🎉 oi ${{ inputs.username }}"
#       - run: printenv | sort
