name: Container on Kubernetes

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string

jobs:
  INIT:
    name: Initialization
    runs-on: ubuntu-latest
    steps:
      - run: echo "Veja dcoumentação da pipeline em"
      
  BUILD:
    name: BUILD
    runs-on: ubuntu-latest
    needs:
      - INIT
    steps:
      - run: echo "🎉 oi ${{ inputs.username }}"
      - run: printenv | sort
      
  TEST:
    name: TEST
    runs-on: ubuntu-latest
    needs:
      - INIT
      - BUILD
      
    steps:
      - run: echo "🎉 oi ${{ inputs.username }}"
      - run: printenv | sort      
      
  CD:
    name: CD
    needs:
      - BUILD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: actions/deploy-kubernetes-argocd.yaml@main
        with:
          image: "the Octocat"
          
      - run: echo "🎉 oi ${{ inputs.username }}"
      - run: printenv | sort
