name: Container on Kubernetes

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string

jobs:

  build:
    name: BUILD
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 oi ${{ inputs.username }}"
      - run: printenv | sort
      
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: actions/hello-world-composite-action@v1
        with:
          who-to-greet: 'Mona the Octocat'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
        
#   TEST:
#     name: TEST
#     runs-on: ubuntu-latest
#     needs:
#       - BUILD
#     steps:
#       - run: echo "🎉 oi ${{ inputs.username }}"
#       - run: printenv | sort      
      
#   CD:
#     name: CD
#     needs:
#       - TEST
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - run: echo "🎉 oi ${{ inputs.username }}"
#       - run: printenv | sort
