name: Container on Kubernetes

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string

jobs:

  BUILD:
    name: BUILD
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 oi ${{ inputs.username }}"
      - run: printenv | sort
      
  TEST:
    name: TEST
    runs-on: ubuntu-latest
    needs:
      - BUILD
    steps:
      - run: echo "🎉 oi ${{ inputs.username }}"
      - run: printenv | sort      
      
  CD:
    name: CD
    needs:
      - TEST
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "🎉 oi ${{ inputs.username }}"
      - run: printenv | sort
