name: Database Migration

on:
  workflow_call:
    inputs:
      SOLUTION_FILE_PATH:
        required: true
        type: string  

      BUILD_CONFIGURATION:
        required: true
        type: string

      OUTPUT_DACPAC_FILE_NAME:
        required: true
        type: string

      ADDITIONAL_SQL_ARGUMENTS:
        required: true
        type: string
 

permissions:
  contents: read


jobs:
  build:
    name: build migration
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{inputs.SOLUTION_FILE_PATH}}

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{inputs.BUILD_CONFIGURATION}} ${{inputs.SOLUTION_FILE_PATH}} 
      
    - run: mkdir -p build-artifacts

    - run: mv mottu.Script\bin\Release\* build-artifacts

    - name: Upload Artifact GitHub Action
      uses: actions/upload-artifact@v2
      with: 
        name: build
        path: build-artifacts

  preview-homologation:
    name: preview homologation
    environment: homologation/review
    runs-on: windows-latest
    needs: build
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: build
          path: .

      - name: Install a SQL Server suite of tools
        uses: potatoqualitee/mssqlsuite@v1.5.1
        with:
          install: sqlpackage

      - run: sqlpackage /action:DeployReport /OutputPath:reports /SourceFile:"${{inputs.OUTPUT_DACPAC_FILE_NAME}}" /TargetConnectionString:"${{secrets.CONNECTION_STRING}}" /p:DropObjectsNotInSource=True /p:BlockOnPossibleDataLoss=false /p:ScriptDatabaseOptions=false /p:DoNotDropObjectTypes="Users;Logins;RoleMembership;Permissions;Credentials;DatabaseScopedCredentials;DatabaseRoles"


  apply-homologation:
    name: apply homologation
    environment: homologation/deploy
    runs-on: windows-latest
    needs: preview-homologation
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: build
          path: .

      - name: Install a SQL Server suite of tools
        uses: potatoqualitee/mssqlsuite@v1.5.1
        with:
          install: sqlpackage


      - run: sqlpackage /Action:Publish /SourceFile:"${{inputs.OUTPUT_DACPAC_FILE_NAME}}" /TargetConnectionString:"${{secrets.CONNECTION_STRING}}" /p:DropObjectsNotInSource=True /p:BlockOnPossibleDataLoss=false /p:ScriptDatabaseOptions=false /p:DoNotDropObjectTypes="Users;Logins;RoleMembership;Permissions;Credentials;DatabaseScopedCredentials;DatabaseRoles"


  preview-production:
    name: preview production
    environment: production/review
    runs-on: windows-latest
    needs: build
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: build
          path: .

      - name: Install a SQL Server suite of tools
        uses: potatoqualitee/mssqlsuite@v1.5.1
        with:
          install: sqlpackage

      - run: sqlpackage /action:DeployReport  /OutputPath:reports /SourceFile:"${{inputs.OUTPUT_DACPAC_FILE_NAME}}" /TargetConnectionString:"${{secrets.CONNECTION_STRING}}" /p:DropObjectsNotInSource=True /p:BlockOnPossibleDataLoss=false /p:ScriptDatabaseOptions=false /p:DoNotDropObjectTypes="Users;Logins;RoleMembership;Permissions;Credentials;DatabaseScopedCredentials;DatabaseRoles"


  apply-production:
    name: apply production
    environment: production/deploy
    runs-on: windows-latest
    needs: preview-production
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: build
          path: .

      - name: Install a SQL Server suite of tools
        uses: potatoqualitee/mssqlsuite@v1.5.1
        with:
          install: sqlpackage

      - run: sqlpackage /Action:Publish /SourceFile:"${{inputs.OUTPUT_DACPAC_FILE_NAME}}" /TargetConnectionString:"${{secrets.CONNECTION_STRING}}" /p:DropObjectsNotInSource=True /p:BlockOnPossibleDataLoss=false /p:ScriptDatabaseOptions=false /p:DoNotDropObjectTypes="Users;Logins;RoleMembership;Permissions;Credentials;DatabaseScopedCredentials;DatabaseRoles"

