name: Database Migration

on:
  workflow_call:
    inputs:
      SOLUTION_FILE_PATH:
        required: true
        type: string  

      BUILD_CONFIGURATION:
        required: true
        type: string

      OUTPUT_DACPAC_FILE_NAME:
        required: true
        type: string

      ADDITIONAL_SQL_ARGUMENTS:
        required: true
        type: string
 

permissions:
  contents: read


jobs:
  build:
    name: build migration
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{inputs.SOLUTION_FILE_PATH}}

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{inputs.BUILD_CONFIGURATION}} ${{inputs.SOLUTION_FILE_PATH}} 
      
    - run: mkdir -p build-artifacts

    - run: mv mottu.Script\bin\Release\* build-artifacts

    - name: Upload Artifact GitHub Action
      uses: actions/upload-artifact@v2
      with: 
        name: build
        path: build-artifacts

  apply-homologation:
    name: apply homologation
    environment: homologation
    runs-on: windows-latest
    needs: build
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: build
          path: .

      - name: Install a SQL Server suite of tools
        uses: potatoqualitee/mssqlsuite@v1.5.1
        with:
          install: sqlpackage


      - run: sqlpackage /Action:Publish /SourceFile:"${{inputs.OUTPUT_DACPAC_FILE_NAME}}" /TargetConnectionString:${{secrets.CONNECTION_STRING}}



      # - name: Azure SQL Deploy (dacpac, file, folder)
      #   uses: XLipcak/sql-action@v1.0.5
      #   with:
      #     # server-name: ${{secrets.SERVER_NAME}}
      #     connection-string: ${{secrets.CONNECTION_STRING}}
      #     dacpac-package: ${{inputs.OUTPUT_DACPAC_FILE_NAME}}
      #     arguments: ${{inputs.ADDITIONAL_SQL_ARGUMENTS}}



  apply-production:
    name: apply production
    environment: production
    runs-on: windows-latest
    needs: build
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: build
          path: .

          

      - name: Azure SQL Deploy (dacpac, file, folder)
        uses: XLipcak/sql-action@v1.0.5
        with:
          server-name: ${{secrets.SERVER_NAME}}
          connection-string: ${{secrets.CONNECTION_STRING}}
          dacpac-package: ${{inputs.OUTPUT_DACPAC_FILE_NAME}}
          arguments: ${{inputs.ADDITIONAL_SQL_ARGUMENTS}}
