name: Database Migration

on:
  workflow_call:

jobs:
  build:
    name: build
    runs-on: windows-latest
    steps:
      - run: echo "build"
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 4.x

      - name: Restore dependencies
        run: dotnet restore    

      - name: Build DotNet
        uses: Elskom/build-dotnet@v1.1.1
        with:
          SOLUTION_FILE_PATH: script.mottu.sln


      # - name: Docker Login
      #   uses: docker/login-action@v2.0.0
      #   with:
      #     # Server address of Docker registry. If not set then will default to Docker Hub
      #     registry: gcr.io/mottu-321312
      #     # Username used to log against the Docker registry
      #     username: # optional
      #     # Password or personal access token used to log against the Docker registry
      #     password: # optional
      #     # Specifies whether the given registry is ECR (auto, true or false)
      #     ecr: # optional, default is auto
      #     # Log out from the Docker registry at the end of a job
      #     logout: # optional, default is true        

      # - run: |
      #     make docker-build
      #   name: 'build images'

      # - name: Setup Node.js environment
      #   uses: actions/setup-node@v3.4.1
      #   with:
      #     node-version-file: .nvmrc
      #     cache: 'npm'

            

      # - run: npm ci || npm install

      # - run: make build-homolog

    