name: Database Migration

on:
  workflow_call:
    inputs:
      PROJECT_FILE_PATH:
        required: true
        type: string  
jobs:
  build:
    name: nuget build & package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup NuGet.exe for use with actions
        uses: NuGet/setup-nuget@v1.0.7
        with:
          nuget-version: 6.3.0

      - name: Setup .NET Core SDK 6.x
        uses: actions/setup-dotnet@v2.1.0
        with:
          dotnet-version: 6.x
          source-url: https://pkgs.dev.azure.com/mottu-ops/_packaging/mottu-ops/nuget/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.AZURE_ARTIFACTS_PAT }} 


      - run: dotnet restore ${{ inputs.PROJECT_FILE_PATH }}


      # - name: Build DotNet
      #   uses: Elskom/build-dotnet@v1.1.1
      #   with:
      #     SOLUTION_FILE_PATH: ${{ inputs.PROJECT_FILE_PATH }}
      #     TEST: true
      #     PACK: true

      - run: |
          printenv | sort
          echo $GITHUB_RUN_ID

      - run: |

          dotnet build -c Release --no-restore ${{ inputs.PROJECT_FILE_PATH }} /p:AssemblyVersion=0.1.$GITHUB_RUN_ID
          dotnet pack --no-build --no-restore -c Release ${{ inputs.PROJECT_FILE_PATH }} 

      - run: |
          ls bin/Release/ || true

      # Publish the package to Azure Artifacts
      - name: 'dotnet publish'
        run: dotnet nuget push --api-key AzureArtifacts bin/Release/*.nupkg 
  
